// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/private.proto

package private

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrivateService_FillPrivateData_FullMethodName = "/PrivateService/FillPrivateData"
	PrivateService_SyncPrivateData_FullMethodName = "/PrivateService/SyncPrivateData"
)

// PrivateServiceClient is the client API for PrivateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrivateServiceClient interface {
	FillPrivateData(ctx context.Context, in *FillPrivateDataRequest, opts ...grpc.CallOption) (*FillPrivateDataResponse, error)
	SyncPrivateData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PrivateDataSyncRequest, PrivateDataSyncResponse], error)
}

type privateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivateServiceClient(cc grpc.ClientConnInterface) PrivateServiceClient {
	return &privateServiceClient{cc}
}

func (c *privateServiceClient) FillPrivateData(ctx context.Context, in *FillPrivateDataRequest, opts ...grpc.CallOption) (*FillPrivateDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FillPrivateDataResponse)
	err := c.cc.Invoke(ctx, PrivateService_FillPrivateData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateServiceClient) SyncPrivateData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PrivateDataSyncRequest, PrivateDataSyncResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PrivateService_ServiceDesc.Streams[0], PrivateService_SyncPrivateData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PrivateDataSyncRequest, PrivateDataSyncResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PrivateService_SyncPrivateDataClient = grpc.BidiStreamingClient[PrivateDataSyncRequest, PrivateDataSyncResponse]

// PrivateServiceServer is the server API for PrivateService service.
// All implementations must embed UnimplementedPrivateServiceServer
// for forward compatibility.
type PrivateServiceServer interface {
	FillPrivateData(context.Context, *FillPrivateDataRequest) (*FillPrivateDataResponse, error)
	SyncPrivateData(grpc.BidiStreamingServer[PrivateDataSyncRequest, PrivateDataSyncResponse]) error
	mustEmbedUnimplementedPrivateServiceServer()
}

// UnimplementedPrivateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrivateServiceServer struct{}

func (UnimplementedPrivateServiceServer) FillPrivateData(context.Context, *FillPrivateDataRequest) (*FillPrivateDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FillPrivateData not implemented")
}
func (UnimplementedPrivateServiceServer) SyncPrivateData(grpc.BidiStreamingServer[PrivateDataSyncRequest, PrivateDataSyncResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SyncPrivateData not implemented")
}
func (UnimplementedPrivateServiceServer) mustEmbedUnimplementedPrivateServiceServer() {}
func (UnimplementedPrivateServiceServer) testEmbeddedByValue()                        {}

// UnsafePrivateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrivateServiceServer will
// result in compilation errors.
type UnsafePrivateServiceServer interface {
	mustEmbedUnimplementedPrivateServiceServer()
}

func RegisterPrivateServiceServer(s grpc.ServiceRegistrar, srv PrivateServiceServer) {
	// If the following call pancis, it indicates UnimplementedPrivateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrivateService_ServiceDesc, srv)
}

func _PrivateService_FillPrivateData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FillPrivateDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateServiceServer).FillPrivateData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivateService_FillPrivateData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateServiceServer).FillPrivateData(ctx, req.(*FillPrivateDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateService_SyncPrivateData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PrivateServiceServer).SyncPrivateData(&grpc.GenericServerStream[PrivateDataSyncRequest, PrivateDataSyncResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PrivateService_SyncPrivateDataServer = grpc.BidiStreamingServer[PrivateDataSyncRequest, PrivateDataSyncResponse]

// PrivateService_ServiceDesc is the grpc.ServiceDesc for PrivateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrivateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PrivateService",
	HandlerType: (*PrivateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FillPrivateData",
			Handler:    _PrivateService_FillPrivateData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncPrivateData",
			Handler:       _PrivateService_SyncPrivateData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/private.proto",
}
